spring:
  application:
    name: SimpleTodo
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/SimpleTodo
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true