spring:
  application:
    name: SimpleTodo
  # DATABASE
  datasource:
    driver-class-name: ${DB_DRIVERCLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true